apiVersion: v1
kind: Service
metadata:
  name: simple-maven
  labels:
    app: simple-maven
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: simple-maven
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-maven
  labels:
    app: simple-maven
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: simple-maven
    spec:
      containers:
      - image: registry.k8sops.mpacops.ca/example/simple-maven:latest
        name: simple-maven
        ports:
        - containerPort: 80
          name: simple-maven
